version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped

  app:
    image: dukavn/express-app
    ports:
      - 8080:8080
    container_name: app
    restart: unless-stopped
